app:
  plugins:
    - name: '@vmware-tanzu/tdp-plugin-home'
      version: '0.0.2'
    - name: '@vrabbi/dev-toolbox-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/chatgpt-wrapper'
      version: '0.2.1'
    - name: '@vmware-tanzu/tdp-plugin-stack-overflow'
      version: '0.0.2'
    - name: '@vmware-tanzu/tdp-plugin-backstage-grafana'
      version: '0.0.2'
    - name: '@vrabbi/github-insights-wrapper'
      version: '0.1.2'
    - name: '@vrabbi/github-pull-requests-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/github-actions-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/tekton-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/harbor-plugin-wrapper'
      version: '0.6.1'
    - name: '@vrabbi/flux-wrapper'
      version: '0.1.2'
    - name: '@vmware-tanzu/tdp-plugin-prometheus'
      version: '0.0.2'
    - name: '@vmware-tanzu/tdp-plugin-techinsights'
      version: '0.0.2'
backend:
  plugins:
    - name: '@vmware-tanzu/tdp-plugin-techinsights-backend'
      version: '0.0.2'
    - name: '@vrabbi/harbor-plugin-wrapper-backend'
      version: '0.6.0'
    - name: '@vrabbi/chatgpt-wrapper-backend'
      version: '0.2.1'
