app:
  plugins:
    - name: '@vrabbi/dev-toolbox-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/chatgpt-wrapper'
      version: '0.2.1'
    - name: '@vrabbi/grafana-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/github-insights-wrapper'
      version: '0.1.2'
    - name: '@vrabbi/security-insights-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/github-issues-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/github-pull-requests-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/github-actions-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/azure-devops-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/tekton-wrapper'
      version: '0.1.2'
    - name: '@vrabbi/jenkins-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/harbor-plugin-wrapper'
      version: '0.6.1'
    - name: '@vrabbi/flux-wrapper'
      version: '0.1.2'
    - name: '@vrabbi/prometheus-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/tech-insights-wrapper'
      version: '0.1.1'
    - name: '@vrabbi/todo-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/k8s-gpt-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/backstage-devtools-wrapper'
      version: '0.2.1'
    - name: '@vrabbi/tech-radar-wrapper'
      version: '0.1.0'
    - name: '@vrabbi/kubecost-wrapper'
      version: '0.1.0'
backend:
  plugins:
    - name: '@vrabbi/tech-insights-wrapper-backend'
      version: '0.1.1'
    - name: '@vrabbi/harbor-plugin-wrapper-backend'
      version: '0.6.0'
    - name: '@vrabbi/chatgpt-wrapper-backend'
      version: '0.2.1'
    - name: '@vrabbi/todo-wrapper-backend'
      version: '0.1.0'
    - name: '@vrabbi/backstage-devtools-wrapper-backend'
      version: '0.1.0'
    - name: '@vrabbi/azure-devops-wrapper-backend'
      version: '0.1.0'
    - name: '@vrabbi/jenkins-wrapper-backend'
      version: '0.1.0'
