apiVersion: backstage.io/v1alpha1
kind: Domain
metadata:
  name: tanzu
  description: Everything related to the Tanzu Application Platform
  links:
    - url: https://www.vrabbi.cloud/post/category/tap/
      title: vRabbi TAP Blogs
      icon: docs
    - url: https://vrabbi.cloud/post/category/tkg/
      title: vRabbi TKG Blogs
      icon: docs
    - url: https://vrabbi.cloud/post/category/carvel/
      title: vRabbi Carvel Blogs
      icon: docs
    - url: https://docs.vmware.com/en/VMware-Tanzu-Application-Platform/index.html
      title: Official TAP Documentation
      icon: docs
    - url: https://docs.vmware.com/en/VMware-Tanzu-Kubernetes-Grid/index.html
      title: Official TKG Documentation
      icon: docs
    - url: https://docs.vmware.com/en/VMware-Tanzu-Mission-Control/index.html
      title: Official TMC Documentation
      icon: docs
    - url: https://carvel.dev
      title: Official Carvel Documentation
      icon: docs
spec:
  owner: cna-team
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Demo Applications
  name: carvel
spec:
  domain: tanzu
  owner: tanzu-admins
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  description: Demo Applications
  name: demo-apps
spec:
  domain: tanzu
  owner: tanzu-admins
